### PR TITLE
Allow operators to disable live reload of Refinery related to changed sampling rules

### PR DESCRIPTION
**Pull request by bixu**
This PR is a workaround for the issue describe in #101

### CODE REVIEW

**Comment by bixu** [comment]
@MikeGoldsmith, do you need me to sign a CLA? Wasn't clear to me from `CONTRIBUTING.md`.

**Review by MikeGoldsmith — APPROVED** [review]
Looks great, thank you.

You do not need to sign a CLA for contributions like this.

**Comment by bixu** [comment]
@MikeGoldsmith, I may have found a templating bug in my change. Will revert this to `Draft` status until I'm done testing.

**Comment by bixu** [comment]
@MikeGoldsmith, I think this latest commit should fix the templating issue I found, plus make the config more consistent.

**Comment by bixu** [comment]
Converting this back to `Draft` status until a finding from @MikeGoldsmith is pulled in (we need to work around [this issue](https://github.com/helm/helm/issues/3308) in Helm).

**Comment by bixu** [comment]
@MikeGoldsmith, pulled in your suggested changes. Nice catch! I find the use of `ternary` a bit hard for my brain to parse, but I guess it's because I'm more used to the Terraform implementation of it, which is a bit friendlier.

**Comment by bixu** [comment]
Thanks for merging this, @MikeGoldsmith :)

**Pull request merged**
